version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    container_name: api-node
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    volumes:
      - ./api:/app
      - /app/node_modules

  ionic:
    build: ./ionic/app-ionic
    container_name: ionic-app
    ports:
      - "${IONIC_PORT}:8100"
    depends_on:
      - api
    volumes:
      - ./ionic/app-ionic:/app
      - /app/node_modules

volumes:
  postgres_data:

